groups/urls.py
from django.urls import path
from django.conf.urls import url
from .views import ListGroups, CreateGroupView, SingleGroup, JoinGroup, LeaveGroup


app_name = "groups"

urlpatterns = [
   path('', ListGroups.as_view(), name="all"),
   path('new/', CreateGroupView.as_view(), name="create"),
   path('posts/in/<int:pk>/', SingleGroup.as_view(), name="single"),
   url(r"^posts/in/(?P<slug>[-\w]+)/$", SingleGroup.as_view(),name="single"),
   url(r"join/(?P<slug>[-\w]+)/$",JoinGroup.as_view(), name="join"),
   url(r"leave/(?P<slug>[-\w]+)/$", LeaveGroup.as_view(),name="leave"),
]

posts/urls.py
from django.urls import path
from .views import PostListView, UserPosts, PostDetailView, PostCreateView, DeletePostView
from django.conf.urls import url


app_name = "posts"

urlpatterns = [
    path('', PostListView.as_view(), name="all"),
    path('new', PostCreateView.as_view(), name="create" ),
    url(r'by/(?P<username>[-\w]+)/$', UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$", PostDetailView.as_view(),name="single"),
    path('delete/<int:pk>', DeletePostView.as_view(), name="delete"),

]

usermanager/urls.py
from django.contrib import admin
from django.urls import path, include
from classroom.views import NurseSignUpView, HelperSignUpView
from .views import HomeView
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('', HomeView.as_view(), name="home"),
    path('accounts/signup/nurse/', NurseSignUpView.as_view(), name='nurse_signup'),
    path('accounts/signup/helper/', HelperSignUpView.as_view(), name='helper_signup'),
    path('groups/', include('groups.urls', namespace="groups")),
    path('posts/', include('posts.urls', namespace="posts")),
]

groups/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model


# Create your models here.
User = get_user_model()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    members = models.ManyToManyField(User, through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="user_groups", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

groups/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, DetailView, View, CreateView, RedirectView
from django.urls import reverse
from .models import Group, GroupMember
from . import models
from django.contrib import messages
from django.db import IntegrityError
from django.contrib.auth.mixins import(LoginRequiredMixin,PermissionRequiredMixin)


# Create your views here.
class CreateGroupView(CreateView):
    fields = ("name", "description")
    model = Group
    context_object_name = "create_group"
    template_name = "group_form.html"

class SingleGroup(DetailView):
    model = Group
    context_object_name = "group_detail"
    template_name = "group_detail.html"

class ListGroups(ListView):
    model = Group
    context_object_name = "list_group"
    template_name = "group_list.html"


class JoinGroup(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})
        
    def get(self, request, *args, **kwargs):
         group = get_object_or_404(Group, slug=self.kwargs.get("slug"))
         
         try:
             GroupMember.objects.create(user=self.request.user,group=group)
         except IntegrityError:
             messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

         else:
             messages.success(self.request,"You are now a member of the {} group.".format(group.name))
    
         return super().get(request, *args, **kwargs)

class LeaveGroup(RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

groups/templates/group_base.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <div class="row">
        {% block pregroup %}
        <!-- group_detail.html goes here -->
        <!-- first part of group_list.html goes here -->
        {% endblock %}

        {% block group_content %}
        <!-- group_form.html goes here -->
        <!-- Second part of group_detail.html goes here -->
        <!-- Second part of group_list.html goes here -->

        {% endblock %}

        {% block postgroup  %}

        {% endblock %}
    </div>
</div>
{% endblock %}

groups/templates/group_detail.html
{% extends "group_base.html" %}

{% block group_content %}
 <div class="col-md-12">
        {% if group_detail.posts.count == 0 %}
            <h2>No posts in this group yet!</h2>
        {% else %}
            <section class="support_details_area">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-9">
                            <div class="dwqa-container">
                                <div class="dwqa-single-question">
                                    <div class="dwqa-breadcrumbs">
                                        <a href="">{{group_detail.name}}</a>
                                        <span class="dwqa-sep"> › </span>
                                        <a href=""> Member Count: {{group_detail.members.count}}</a>
                                        <span class="dwqa-sep"> › </span>
                                        <span class="dwqa-current"> 
                                           
                                        </span>
                                            <h2>[HELP]: {{group_detail.description}}</h1>

                                    </div>
                                    <!-- Ends: .dwqa-breadcrumbs -->
                                    
        {% for post in group_detail.posts.all %}
            <!-- Start: .dwqa-question-item -->
            <div class="dwqa-question-item">
                <div class="dwqa-question-vote" data-nonce="d7368a240e" data-post="6395">
                    <span class="dwqa-vote-count">0</span>
                    <a class="dwqa-vote dwqa-vote-up" href="#">Vote Up</a>
                    <a class="dwqa-vote dwqa-vote-down" href="#">Vote Down</a>
                </div>
                </br>
                </br>
                <div class="dwqa-question-meta">
                        <span>
                            <a href="">
                                <img alt="" src="static/images/dw-avatar.png" class="avatar avatar-48 photo"
                                    height="48" width="48">{{post.user.username}}</a> asked on {{ post.created_at }}</span>
                    <span class="dwqa-question-actions"></span>
                </div>
                <div class="dwqa-question-content">
                    <p>{{ post.message }}</p>
                </div>
            </div>
            <!-- Ends: .dwqa-question-item -->
        {% endfor %}              
                </div>
                <!-- Ends: .dwqa-single-question -->
            </div>
            <!-- Ends: .dwqa-container -->
        </div>
        <!-- Ends: .col-lg-9 -->      

                          <div class="col-lg-3">
                    <aside class="sidebar support--sidebar">
                    <a href="login.html" class="login_promot">Login to Ask a Question</a>
                     {% if user in group_detail.members.all %}
                            <a href="{% url 'groups:leave' slug=group_detail.slug %}" class="btn-danger login_promot"> Leave Group</a>
                    {% else %}
                            <a href="{% url 'groups:join' slug=group_detail.slug %}" class="login_promot"> Join Group</a>
                    {% endif %} 
                    <div class="sidebar-card card--forum_categories">
                        <div class="card-title">
                            <h4>Categories</h4>
                        </div>
                        <div class="collapsible-content">
                            <ul class="card-content">
                                <li>
                                    <a href="#">
                                        Wordpress
                                        <span class="item-count">35</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Support Center
                                        <span class="item-count"> 45</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        General Topics
                                        <span class="item-count">13</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Pre-Sales
                                        <span class="item-count">08</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Purchases
                                        <span class="item-count">34</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Billing
                                        <span class="item-count">78</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Testimonials
                                        <span class="item-count">26</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- end /.collapsible_content -->
                    </div>
                    <!-- end .card--forum_categories -->

                    <div class="sidebar-card card--top_discussion">
                        <div class="card-title">
                            <h4>Popular Questions</h4>
                        </div>
                        <div class="collapsible-content">
                            <ul class="card-content">
                                <li>
                                    <a href="#">How to pin a sticky ques tion to the top of the ques tions page?
                                        <span>2 Weeks Ago</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">How can I delete more than one post at a time?
                                        <span>2 Weeks Ago</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">What are the guidelines for ratings and reviews?
                                        <span>2 Weeks Ago</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">How can I delete more than one post at a time?
                                        <span>2 Weeks Ago</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- end /.collapsible_content -->
                    </div>
                    <!-- end .card--forum_categories -->
                </aside>
                <!-- end .sidebar -->
            </div>
            <!-- end .col-lg-3 -->    
                    </div>
                    <!-- end .row -->
                </div>
                <!-- end .container -->
            </section>
            
        {% endif %}

    
</div>

{% endblock %}

groups/templates/group_form.html
{% block group_content %}
<h4>Create A New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{{ form.as_p }}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

groups/templates/group_list.html
{% extends "group_base.html" %}
{% block pregroup %}
      <div class="col-md-4">
      	<div class="content">
      		{% if user.is_authenticated %}
        		<h2>
        			Welcome back
        			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
        		</h2>
          {% endif %}

          <h2>Groups</h2>
          <p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
        </div>
        {% if user.is_authenticated %}
      	 <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
      	{% endif %}
    </div>
  {% endblock %}

{% block group_content %}
    <div class="col-md-8">
      <div class="list-group">
        {% for group in object_list %}
            <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
                 <h3 class="title list-group-item-heading">{{ group.name }}</h3>
              <div class="list-group-item-text container-fluid">
                <div class="row">
                  <div class="col-md-4">
                    <span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
                  </div>
                  <div class="col-md-4">
                    <span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
                  </div>
                </div>
              </div>
            </a>
        {% endfor %}
      </div>
    </div>
  {% endblock %}