posts/urls.py
from django.urls import path
from .views import PostListView, UserPosts, PostDetailView, PostCreateView, DeletePostView
from django.conf.urls import url


app_name = "posts"

urlpatterns = [
    path('', PostListView.as_view(), name="all"),
    path('new', PostCreateView.as_view(), name="create" ),
    url(r'by/(?P<username>[-\w]+)/$', UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$", PostDetailView.as_view(),name="single"),
    path('delete/<int:pk>', DeletePostView.as_view(), name="delete"),

]

usermanager/urls.py
from django.contrib import admin
from django.urls import path, include
from classroom.views import NurseSignUpView, HelperSignUpView
from .views import HomeView
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('', HomeView.as_view(), name="home"),
    path('accounts/signup/nurse/', NurseSignUpView.as_view(), name='nurse_signup'),
    path('accounts/signup/helper/', HelperSignUpView.as_view(), name='helper_signup'),
    path('groups/', include('groups.urls', namespace="groups")),
    path('posts/', include('posts.urls', namespace="posts")),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from groups.models import Group


User = get_user_model()
# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True, auto_now_add=False)
    message = models.TextField()
    group = models.ForeignKey(Group, related_name="posts", null=True, 
                             blank=True, on_delete=models.CASCADE)


    def __str__(self):
        return self.message
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
       return reverse(
           "posts:single",
           kwargs={
               "username": self.user.username,
               "pk": self.pk
           }
       )


    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]
    

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = Post
    

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is None:
            self.fields["group"].queryset = (
                Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

posts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (TemplateView, ListView, DetailView, 
                                 View, CreateView, RedirectView, DeleteView)
from django.contrib import messages                       
from django.http import Http404
from braces.views import SelectRelatedMixin

from .forms import PostForm
from .models import Post
from django.contrib.auth import get_user_model

User = get_user_model()
# Create your views here.

class PostListView(ListView):
    model = Post
    select_related = ("user", "group")
    context_object_name = "post_list"
    template_name = "post_list.html"


class UserPosts(ListView):
    model = Post
    template_name = "user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context

class PostDetailView(SelectRelatedMixin, DetailView):
    model = Post
    select_related = ("user", "group")
    template_name = "post_detail.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )

class PostCreateView(LoginRequiredMixin, CreateView):
    fields = ('message','group')
    model = Post
    template_name = "post_form.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePostView(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")
    template_name = "post_confirm_delete.html"
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

    
    

posts/templates/_post.html
{% comment %} <div class="post media">
  <h3>{{ post.message }}</h3>

  <div class="media-body">
    <strong>{{post.user.username}}</strong>
    <h5 class="media-heading">
  			<span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
  			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
  			{% if post.group %}
  			    <span class="group-name">in <a href="#">{{ post.group.name }}</a></span>
  			{% endif %}


  		</h5>

      <div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
  </div>
</div> {% endcomment %}

 {% comment %} <section class="support_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="dwqa-container">
                    <div class="dwqa-single-question">
                        <div class="dwqa-breadcrumbs">
                            <a href="">Support Forum</a>
                            <span class="dwqa-sep"> › </span>
                            <a href="">Category: Item Discussion</a>
                            <span class="dwqa-sep"> › </span>
                            <span class="dwqa-current">Responsive Website Footer Menu</span>
                        </div>
                        <!-- Ends: .dwqa-breadcrumbs -->
                        
                        <!-- Start: .dwqa-question-item -->
                            
                            <div class="dwqa-question-item">
                                <div class="dwqa-question-vote" data-nonce="d7368a240e" data-post="6395">
                                    <span class="dwqa-vote-count">0</span>
                                    <a class="dwqa-vote dwqa-vote-up" href="#">Vote Up</a>
                                    <a class="dwqa-vote dwqa-vote-down" href="#">Vote Down</a>
                                </div>
                                <div class="dwqa-question-meta">
                                        <span>
                                            <a href="">
                                                <img alt="" src="static/images/dw-avatar.png" class="avatar avatar-48 photo"
                                                    height="48" width="48">{{post.user.username}}</a> asked on {{ post.created_at }}</span>
                                    <span class="dwqa-question-actions"></span>
                                </div>
                                <div class="dwqa-question-content">
                                    <p>{{ post.message }}</p>
                                </div>
                            </div>

                        <!-- Ends: .dwqa-question-item -->
                        <div class="dwqa-answers">
                            <div class="dwqa-answers-title"><h5>4 Answers</h5></div>
                            <div class="dwqa-answers-list">
                                <div class="dwqa-answer-item">
                                    <div class="dwqa-answer-vote" data-nonce="5d2ccf7ff2" data-post="6399">
                                        <span class="dwqa-vote-count">0</span>
                                        <a class="dwqa-vote dwqa-vote-up" href="#">Vote Up</a>
                                        <a class="dwqa-vote dwqa-vote-down" href="#">Vote Down</a>
                                    </div>
                                    <div class="dwqa-answer-meta">
                                            <span>
                                                <a href="">
                                                    <img alt="" src="images/dw-avatar2.png"
                                                         class="avatar avatar-48 photo" height="48" width="48">AazzTech</a>
                                                <span class="dwqa-label dwqa-staff">Staff</span> answered 2 years ago</span>
                                    </div>
                                    <div class="dwqa-answer-content">
                                        <p>Hi Josh,
                                            <br> Can you give your website link so that we can check and give you the
                                            code
                                            necessary to change the font?&nbsp;</p>
                                    </div>
                                </div>
                                
                            </div>
                            <!-- dwqa-answers-list -->
                        </div>
                        <!-- Ends: .dwqa-answers -->
                    </div>
                    <!-- Ends: .dwqa-single-question -->
                </div>
                <!-- Ends: .dwqa-container -->
            </div>
            <!-- Ends: .col-lg-9 -->

            <div class="col-lg-3">
                <aside class="sidebar support--sidebar">
                    <a href="login.html" class="login_promot">Login to Ask a Question</a>

                    <div class="sidebar-card card--forum_categories">
                        <div class="card-title">
                            <h4>Categories</h4>
                        </div>
                        <div class="collapsible-content">
                            <ul class="card-content">
                                <li>
                                    <a href="#">
                                        Wordpress
                                        <span class="item-count">35</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Support Center
                                        <span class="item-count"> 45</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        General Topics
                                        <span class="item-count">13</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Pre-Sales
                                        <span class="item-count">08</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Purchases
                                        <span class="item-count">34</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Billing
                                        <span class="item-count">78</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Testimonials
                                        <span class="item-count">26</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- end /.collapsible_content -->
                    </div>
                    <!-- end .card--forum_categories -->

                    <div class="sidebar-card card--top_discussion">
                        <div class="card-title">
                            <h4>Popular Questions</h4>
                        </div>
                        <div class="collapsible-content">
                            <ul class="card-content">
                                <li>
                                    <a href="#">How to pin a sticky ques tion to the top of the ques tions page?
                                        <span>2 Weeks Ago</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">How can I delete more than one post at a time?
                                        <span>2 Weeks Ago</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">What are the guidelines for ratings and reviews?
                                        <span>2 Weeks Ago</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">How can I delete more than one post at a time?
                                        <span>2 Weeks Ago</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- end /.collapsible_content -->
                    </div>
                    <!-- end .card--forum_categories -->
                </aside>
                <!-- end .sidebar -->
            </div>
            <!-- end .col-lg-3 -->
        </div>
        <!-- end .row -->
    </div>
    <!-- end .container -->
</section>
<!--================================
        END FORUM DETAILS AREA
=================================-->
<section class="support_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="dwqa-container">
                    <div class="dwqa-single-question">
                        <div class="dwqa-breadcrumbs">
                            <a href="">Support Forum</a>
                            <span class="dwqa-sep"> › </span>
                            <a href="">Category: Item Discussion</a>
                            <span class="dwqa-sep"> › </span>
                            <span class="dwqa-current">Responsive Website Footer Menu</span>
                        </div>
                        <!-- Ends: .dwqa-breadcrumbs -->              
                    </div>
                    <!-- Ends: .dwqa-single-question -->
                </div>
                <!-- Ends: .dwqa-container -->
            </div>
            <!-- Ends: .col-lg-9 -->          
        </div>
        <!-- end .row -->
    </div>
    <!-- end .container -->
</section>

posts/templates/post_base.html
{% extends "base.html" %}

{% block content %}
  <div class="post-page">
    <div class="container">
      <div class="row">
          {% block prepost %}
          {% endblock %}

          {% block post_content %}
          {% endblock %}

          {% block post_post %}
          {% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

posts/templates/post_confirm_delete.html
{% extends "post_base.html" %}

{% block post_content %}
  <h3>Are you sure you want to delete this post?</h3>

  <div class="posts">
    {% include "_post.html" with post=object hide_delete=True %}
  </div>

  <form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
    <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
  </form>
{% endblock %}

posts/templates/post_detail.html
{% extends "post_base.html" %}

{% block post_content %}
  <div class="col-md-8">
    {% include "_post.html" %}
  </div>
{% endblock %}

posts/templates/post_form.html
{% extends "post_base.html" %}

{% block post_content %}
  <h4>Create a New Post </h4>
  <form  action="{% url 'posts:create' %}" method="POST" id="postForm">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="Post" class="btn btn-primary btn-large">
  </form>
  {% endblock %}

posts/templates/post_list.html
{% extends "post_base.html" %}

{% block prepost %}
  <div class="col-md-4">
  {% if request.user.is_authenticated %}
    <div class="card card-with-shadow">
        <div class="content">
        <h5 class="title">Your Groups</h5>
        <ul class="list-unstyled">

            {% for member_group in get_user_groups %}
            <li class="group li-with-bullet">
            <a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
            </li>bn 
            {% endfor %}

        </ul>
        </div>
    </div>
  {% endif %}
  <div class="card card-with-shadow">
    <div class="content">
      <h5 class="title">All groups</h5>
      <ul class="list-unstyled">
        {# {% get_other_groups as other_groups %}#}
       {% for other_group in get_other_groups %}
          <li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
        {% endfor %}
      </ul>
  </div>
  </div>
  </div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
        {{post.message}}
  {% include "_post.html" %}
	{% endfor %}
</div>
{% endblock %}

posts/templates/user_post_list.html
{% extends "post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "_post.html" %}
	{% endfor %}
</div>
{% endblock %}