posts/urls.py
from django.urls import path
from .views import PostListView, UserPosts, PostDetailView, PostCreateView, DeletePostView
from django.conf.urls import url


app_name = "posts"

urlpatterns = [
    path('', PostListView.as_view(), name="all"),
    path('new', PostCreateView.as_view(), name="create" ),
    url(r'by/(?P<username>[-\w]+)/$', UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$", PostDetailView.as_view(),name="single"),
    path('delete/<int:pk>', DeletePostView.as_view(), name="delete"),

]

usermanager/urls.py
from django.contrib import admin
from django.urls import path, include
from classroom.views import NurseSignUpView, HelperSignUpView
from .views import HomeView
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('', HomeView.as_view(), name="home"),
    path('accounts/signup/nurse/', NurseSignUpView.as_view(), name='nurse_signup'),
    path('accounts/signup/helper/', HelperSignUpView.as_view(), name='helper_signup'),
    path('groups/', include('groups.urls', namespace="groups")),
    path('posts/', include('posts.urls', namespace="posts")),
]

templates/base.html
<DOCTYPE html>
{% load compress %}
{% load static %}

<html>
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    {% comment %} {% compress css %}
      <link type="text/x-scss" href="{% static 'sass/style.scss' %}" rel="stylesheet" media="screen">
      <link type="text/x-scss" href="{% static 'css/bootstrap/bootstrap.scss' %}" rel="stylesheet" media="screen">
    {% endcompress %} {% endcomment %}
  
  <!-- FONTAWESOME  -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  
  
  </head>
  <body>
    <nav class="navbar  mynav" role="navigation" id="navbar">
  			<div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
            <ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                      <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                      {% comment %} <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li> {% endcomment %}
    						{% else %}
    						      <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
    						      {% comment %} <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> {% endcomment %}
    						{% endif %}
    					</ul>
          </div>
    	</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}
        </div>
  <canvas id="canvas"></canvas>
</body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>Hello, Welcome to Simple Social</h1>
  <p>The funniest and most engaged community of the web</p>
{% endblock %}